/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';
import {
  Enseignant,
} from './global/enseignant';
import {
  Formation,
} from './global/formation';
import {
  Promotion,
} from './global/promotion';
import {
  Qualificatif,
} from './global/qualificatif';
import {
  Rubrique,
} from './global/rubrique';


export namespace Components {

  interface AdmHeader {}
  interface AdmHeaderAttributes extends StencilHTMLAttributes {}

  interface AdmHome {}
  interface AdmHomeAttributes extends StencilHTMLAttributes {}

  interface AdmRoot {}
  interface AdmRootAttributes extends StencilHTMLAttributes {}

  interface EnsAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EnsAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnsCard {
    'enseignant': Enseignant;
  }
  interface EnsCardAttributes extends StencilHTMLAttributes {
    'enseignant'?: Enseignant;
    'onEnseignantSupprime'?: (event: CustomEvent) => void;
  }

  interface EnsDetail {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EnsDetailAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnsForm {
    'enseignant': Enseignant;
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
  }
  interface EnsFormAttributes extends StencilHTMLAttributes {
    'enseignant'?: Enseignant;
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
  }

  interface EnsHome {}
  interface EnsHomeAttributes extends StencilHTMLAttributes {}

  interface EnsSearch {}
  interface EnsSearchAttributes extends StencilHTMLAttributes {}

  interface FormAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormDetail {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormDetailAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormForm {
    'formation': Formation;
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
  }
  interface FormFormAttributes extends StencilHTMLAttributes {
    'formation'?: Formation;
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
  }

  interface FormHome {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormSearch {
    'history': RouterHistory;
  }
  interface FormSearchAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface PromoAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface PromoAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface PromoDetail {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface PromoDetailAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface PromoForm {
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
    'promotion': Promotion;
  }
  interface PromoFormAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
    'promotion'?: Promotion;
  }

  interface PromoHome {
    'history': RouterHistory;
  }
  interface PromoHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface PromoSearch {
    'history': RouterHistory;
  }
  interface PromoSearchAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface PromoTable {
    'history': RouterHistory;
    'promotions': Promotion[];
  }
  interface PromoTableAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'onPromotionSupprime'?: (event: CustomEvent) => void;
    'promotions'?: Promotion[];
  }

  interface EtuCard {
    'etudiant': any;
  }
  interface EtuCardAttributes extends StencilHTMLAttributes {
    'etudiant'?: any;
    'onEtudiantSupprime'?: (event: CustomEvent) => void;
  }

  interface EtuHome {
    'match': MatchResults;
  }
  interface EtuHomeAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EvaeHeader {}
  interface EvaeHeaderAttributes extends StencilHTMLAttributes {}

  interface EvaeHome {}
  interface EvaeHomeAttributes extends StencilHTMLAttributes {}

  interface EvaeRoot {}
  interface EvaeRootAttributes extends StencilHTMLAttributes {}

  interface FormCard {
    'formation': Formation;
  }
  interface FormCardAttributes extends StencilHTMLAttributes {
    'formation'?: Formation;
    'onFormationSupprime'?: (event: CustomEvent) => void;
  }

  interface FormHome1 {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormHome1Attributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface UeAccordion {
    'match': MatchResults;
  }
  interface UeAccordionAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface QualiHome {
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
    'qualificatif': Qualificatif;
  }
  interface QualiHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
    'onQualifSupprime'?: (event: CustomEvent) => void;
    'qualificatif'?: Qualificatif;
  }

  interface QstHome {
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
  }
  interface QstHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
    'onQuestionSupprime'?: (event: CustomEvent) => void;
  }

  interface RubHome {
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
    'rubrique': Rubrique;
  }
  interface RubHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
    'onRubriqueSupprime'?: (event: CustomEvent) => void;
    'rubrique'?: Rubrique;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AdmHeader': Components.AdmHeader;
    'AdmHome': Components.AdmHome;
    'AdmRoot': Components.AdmRoot;
    'EnsAdd': Components.EnsAdd;
    'EnsCard': Components.EnsCard;
    'EnsDetail': Components.EnsDetail;
    'EnsForm': Components.EnsForm;
    'EnsHome': Components.EnsHome;
    'EnsSearch': Components.EnsSearch;
    'FormAdd': Components.FormAdd;
    'FormDetail': Components.FormDetail;
    'FormForm': Components.FormForm;
    'FormHome': Components.FormHome;
    'FormSearch': Components.FormSearch;
    'PromoAdd': Components.PromoAdd;
    'PromoDetail': Components.PromoDetail;
    'PromoForm': Components.PromoForm;
    'PromoHome': Components.PromoHome;
    'PromoSearch': Components.PromoSearch;
    'PromoTable': Components.PromoTable;
    'EtuCard': Components.EtuCard;
    'EtuHome': Components.EtuHome;
    'EvaeHeader': Components.EvaeHeader;
    'EvaeHome': Components.EvaeHome;
    'EvaeRoot': Components.EvaeRoot;
    'FormCard': Components.FormCard;
    'FormHome1': Components.FormHome1;
    'UeAccordion': Components.UeAccordion;
    'QualiHome': Components.QualiHome;
    'QstHome': Components.QstHome;
    'RubHome': Components.RubHome;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'adm-header': Components.AdmHeaderAttributes;
    'adm-home': Components.AdmHomeAttributes;
    'adm-root': Components.AdmRootAttributes;
    'ens-add': Components.EnsAddAttributes;
    'ens-card': Components.EnsCardAttributes;
    'ens-detail': Components.EnsDetailAttributes;
    'ens-form': Components.EnsFormAttributes;
    'ens-home': Components.EnsHomeAttributes;
    'ens-search': Components.EnsSearchAttributes;
    'form-add': Components.FormAddAttributes;
    'form-detail': Components.FormDetailAttributes;
    'form-form': Components.FormFormAttributes;
    'form-home': Components.FormHomeAttributes;
    'form-search': Components.FormSearchAttributes;
    'promo-add': Components.PromoAddAttributes;
    'promo-detail': Components.PromoDetailAttributes;
    'promo-form': Components.PromoFormAttributes;
    'promo-home': Components.PromoHomeAttributes;
    'promo-search': Components.PromoSearchAttributes;
    'promo-table': Components.PromoTableAttributes;
    'etu-card': Components.EtuCardAttributes;
    'etu-home': Components.EtuHomeAttributes;
    'evae-header': Components.EvaeHeaderAttributes;
    'evae-home': Components.EvaeHomeAttributes;
    'evae-root': Components.EvaeRootAttributes;
    'form-card': Components.FormCardAttributes;
    'form-home1': Components.FormHome1Attributes;
    'ue-accordion': Components.UeAccordionAttributes;
    'quali-home': Components.QualiHomeAttributes;
    'qst-home': Components.QstHomeAttributes;
    'rub-home': Components.RubHomeAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLAdmHeaderElement extends Components.AdmHeader, HTMLStencilElement {}
  var HTMLAdmHeaderElement: {
    prototype: HTMLAdmHeaderElement;
    new (): HTMLAdmHeaderElement;
  };

  interface HTMLAdmHomeElement extends Components.AdmHome, HTMLStencilElement {}
  var HTMLAdmHomeElement: {
    prototype: HTMLAdmHomeElement;
    new (): HTMLAdmHomeElement;
  };

  interface HTMLAdmRootElement extends Components.AdmRoot, HTMLStencilElement {}
  var HTMLAdmRootElement: {
    prototype: HTMLAdmRootElement;
    new (): HTMLAdmRootElement;
  };

  interface HTMLEnsAddElement extends Components.EnsAdd, HTMLStencilElement {}
  var HTMLEnsAddElement: {
    prototype: HTMLEnsAddElement;
    new (): HTMLEnsAddElement;
  };

  interface HTMLEnsCardElement extends Components.EnsCard, HTMLStencilElement {}
  var HTMLEnsCardElement: {
    prototype: HTMLEnsCardElement;
    new (): HTMLEnsCardElement;
  };

  interface HTMLEnsDetailElement extends Components.EnsDetail, HTMLStencilElement {}
  var HTMLEnsDetailElement: {
    prototype: HTMLEnsDetailElement;
    new (): HTMLEnsDetailElement;
  };

  interface HTMLEnsFormElement extends Components.EnsForm, HTMLStencilElement {}
  var HTMLEnsFormElement: {
    prototype: HTMLEnsFormElement;
    new (): HTMLEnsFormElement;
  };

  interface HTMLEnsHomeElement extends Components.EnsHome, HTMLStencilElement {}
  var HTMLEnsHomeElement: {
    prototype: HTMLEnsHomeElement;
    new (): HTMLEnsHomeElement;
  };

  interface HTMLEnsSearchElement extends Components.EnsSearch, HTMLStencilElement {}
  var HTMLEnsSearchElement: {
    prototype: HTMLEnsSearchElement;
    new (): HTMLEnsSearchElement;
  };

  interface HTMLFormAddElement extends Components.FormAdd, HTMLStencilElement {}
  var HTMLFormAddElement: {
    prototype: HTMLFormAddElement;
    new (): HTMLFormAddElement;
  };

  interface HTMLFormDetailElement extends Components.FormDetail, HTMLStencilElement {}
  var HTMLFormDetailElement: {
    prototype: HTMLFormDetailElement;
    new (): HTMLFormDetailElement;
  };

  interface HTMLFormFormElement extends Components.FormForm, HTMLStencilElement {}
  var HTMLFormFormElement: {
    prototype: HTMLFormFormElement;
    new (): HTMLFormFormElement;
  };

  interface HTMLFormHomeElement extends Components.FormHome, HTMLStencilElement {}
  var HTMLFormHomeElement: {
    prototype: HTMLFormHomeElement;
    new (): HTMLFormHomeElement;
  };

  interface HTMLFormSearchElement extends Components.FormSearch, HTMLStencilElement {}
  var HTMLFormSearchElement: {
    prototype: HTMLFormSearchElement;
    new (): HTMLFormSearchElement;
  };

  interface HTMLPromoAddElement extends Components.PromoAdd, HTMLStencilElement {}
  var HTMLPromoAddElement: {
    prototype: HTMLPromoAddElement;
    new (): HTMLPromoAddElement;
  };

  interface HTMLPromoDetailElement extends Components.PromoDetail, HTMLStencilElement {}
  var HTMLPromoDetailElement: {
    prototype: HTMLPromoDetailElement;
    new (): HTMLPromoDetailElement;
  };

  interface HTMLPromoFormElement extends Components.PromoForm, HTMLStencilElement {}
  var HTMLPromoFormElement: {
    prototype: HTMLPromoFormElement;
    new (): HTMLPromoFormElement;
  };

  interface HTMLPromoHomeElement extends Components.PromoHome, HTMLStencilElement {}
  var HTMLPromoHomeElement: {
    prototype: HTMLPromoHomeElement;
    new (): HTMLPromoHomeElement;
  };

  interface HTMLPromoSearchElement extends Components.PromoSearch, HTMLStencilElement {}
  var HTMLPromoSearchElement: {
    prototype: HTMLPromoSearchElement;
    new (): HTMLPromoSearchElement;
  };

  interface HTMLPromoTableElement extends Components.PromoTable, HTMLStencilElement {}
  var HTMLPromoTableElement: {
    prototype: HTMLPromoTableElement;
    new (): HTMLPromoTableElement;
  };

  interface HTMLEtuCardElement extends Components.EtuCard, HTMLStencilElement {}
  var HTMLEtuCardElement: {
    prototype: HTMLEtuCardElement;
    new (): HTMLEtuCardElement;
  };

  interface HTMLEtuHomeElement extends Components.EtuHome, HTMLStencilElement {}
  var HTMLEtuHomeElement: {
    prototype: HTMLEtuHomeElement;
    new (): HTMLEtuHomeElement;
  };

  interface HTMLEvaeHeaderElement extends Components.EvaeHeader, HTMLStencilElement {}
  var HTMLEvaeHeaderElement: {
    prototype: HTMLEvaeHeaderElement;
    new (): HTMLEvaeHeaderElement;
  };

  interface HTMLEvaeHomeElement extends Components.EvaeHome, HTMLStencilElement {}
  var HTMLEvaeHomeElement: {
    prototype: HTMLEvaeHomeElement;
    new (): HTMLEvaeHomeElement;
  };

  interface HTMLEvaeRootElement extends Components.EvaeRoot, HTMLStencilElement {}
  var HTMLEvaeRootElement: {
    prototype: HTMLEvaeRootElement;
    new (): HTMLEvaeRootElement;
  };

  interface HTMLFormCardElement extends Components.FormCard, HTMLStencilElement {}
  var HTMLFormCardElement: {
    prototype: HTMLFormCardElement;
    new (): HTMLFormCardElement;
  };

  interface HTMLFormHome1Element extends Components.FormHome1, HTMLStencilElement {}
  var HTMLFormHome1Element: {
    prototype: HTMLFormHome1Element;
    new (): HTMLFormHome1Element;
  };

  interface HTMLUeAccordionElement extends Components.UeAccordion, HTMLStencilElement {}
  var HTMLUeAccordionElement: {
    prototype: HTMLUeAccordionElement;
    new (): HTMLUeAccordionElement;
  };

  interface HTMLQualiHomeElement extends Components.QualiHome, HTMLStencilElement {}
  var HTMLQualiHomeElement: {
    prototype: HTMLQualiHomeElement;
    new (): HTMLQualiHomeElement;
  };

  interface HTMLQstHomeElement extends Components.QstHome, HTMLStencilElement {}
  var HTMLQstHomeElement: {
    prototype: HTMLQstHomeElement;
    new (): HTMLQstHomeElement;
  };

  interface HTMLRubHomeElement extends Components.RubHome, HTMLStencilElement {}
  var HTMLRubHomeElement: {
    prototype: HTMLRubHomeElement;
    new (): HTMLRubHomeElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'adm-header': HTMLAdmHeaderElement
    'adm-home': HTMLAdmHomeElement
    'adm-root': HTMLAdmRootElement
    'ens-add': HTMLEnsAddElement
    'ens-card': HTMLEnsCardElement
    'ens-detail': HTMLEnsDetailElement
    'ens-form': HTMLEnsFormElement
    'ens-home': HTMLEnsHomeElement
    'ens-search': HTMLEnsSearchElement
    'form-add': HTMLFormAddElement
    'form-detail': HTMLFormDetailElement
    'form-form': HTMLFormFormElement
    'form-home': HTMLFormHomeElement
    'form-search': HTMLFormSearchElement
    'promo-add': HTMLPromoAddElement
    'promo-detail': HTMLPromoDetailElement
    'promo-form': HTMLPromoFormElement
    'promo-home': HTMLPromoHomeElement
    'promo-search': HTMLPromoSearchElement
    'promo-table': HTMLPromoTableElement
    'etu-card': HTMLEtuCardElement
    'etu-home': HTMLEtuHomeElement
    'evae-header': HTMLEvaeHeaderElement
    'evae-home': HTMLEvaeHomeElement
    'evae-root': HTMLEvaeRootElement
    'form-card': HTMLFormCardElement
    'form-home1': HTMLFormHome1Element
    'ue-accordion': HTMLUeAccordionElement
    'quali-home': HTMLQualiHomeElement
    'qst-home': HTMLQstHomeElement
    'rub-home': HTMLRubHomeElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'adm-header': HTMLAdmHeaderElement;
    'adm-home': HTMLAdmHomeElement;
    'adm-root': HTMLAdmRootElement;
    'ens-add': HTMLEnsAddElement;
    'ens-card': HTMLEnsCardElement;
    'ens-detail': HTMLEnsDetailElement;
    'ens-form': HTMLEnsFormElement;
    'ens-home': HTMLEnsHomeElement;
    'ens-search': HTMLEnsSearchElement;
    'form-add': HTMLFormAddElement;
    'form-detail': HTMLFormDetailElement;
    'form-form': HTMLFormFormElement;
    'form-home': HTMLFormHomeElement;
    'form-search': HTMLFormSearchElement;
    'promo-add': HTMLPromoAddElement;
    'promo-detail': HTMLPromoDetailElement;
    'promo-form': HTMLPromoFormElement;
    'promo-home': HTMLPromoHomeElement;
    'promo-search': HTMLPromoSearchElement;
    'promo-table': HTMLPromoTableElement;
    'etu-card': HTMLEtuCardElement;
    'etu-home': HTMLEtuHomeElement;
    'evae-header': HTMLEvaeHeaderElement;
    'evae-home': HTMLEvaeHomeElement;
    'evae-root': HTMLEvaeRootElement;
    'form-card': HTMLFormCardElement;
    'form-home1': HTMLFormHome1Element;
    'ue-accordion': HTMLUeAccordionElement;
    'quali-home': HTMLQualiHomeElement;
    'qst-home': HTMLQstHomeElement;
    'rub-home': HTMLRubHomeElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
